import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const BYE = {
  ARI: 8,
  ATL: 5,
  BAL: 14,
  BUF: 12,
  CAR: 14,
  CHI: 5,
  CIN: 12,
  CLE: 9,
  DAL: 7,
  DEN: 14,
  DET: 8,
  GB: 5,
  HOU: 14,
  IND: 11,
  JAX: 12,
  KC: 6,
  LAC: 12,
  LAR: 8,
  LV: 8,
  MIA: 6,
  MIN: 6,
  NE: 14,
  NO: 12,
  NYG: 11,
  NYJ: 12,
  PHI: 9,
  PIT: 9,
  SEA: 8,
  SF: 9,
  TB: 9,
  TEN: 10,
  WAS: 12,
};

/** ADP-ordered skill players, then specialists. name|pos|team */
const RAW = [
  "Ja'Marr Chase|WR|CIN",
  "Bijan Robinson|RB|ATL",
  "Justin Jefferson|WR|MIN",
  "Saquon Barkley|RB|PHI",
  "CeeDee Lamb|WR|DAL",
  "Jahmyr Gibbs|RB|DET",
  "Amon-Ra St. Brown|WR|DET",
  "Nico Collins|WR|HOU",
  "Malik Nabers|WR|NYG",
  "Puka Nacua|WR|LAR",
  "Brian Thomas Jr.|WR|JAX",
  "Derrick Henry|RB|BAL",
  "Christian McCaffrey|RB|SF",
  "A.J. Brown|WR|PHI",
  "Drake London|WR|ATL",
  "De'Von Achane|RB|MIA",
  "Jonathan Taylor|RB|IND",
  "Josh Jacobs|RB|GB",
  "Josh Allen|QB|BUF",
  "Lamar Jackson|QB|BAL",
  "Tyreek Hill|WR|MIA",
  "Jalen Hurts|QB|PHI",
  "Kyren Williams|RB|LAR",
  "Breece Hall|RB|NYJ",
  "Tee Higgins|WR|CIN",
  "Davante Adams|WR|LAR",
  "Mike Evans|WR|TB",
  "DK Metcalf|WR|PIT",
  "James Cook|RB|BUF",
  "Garrett Wilson|WR|NYJ",
  "Marvin Harrison Jr.|WR|ARI",
  "Ladd McConkey|WR|LAC",
  "Jaxon Smith-Njigba|WR|SEA",
  "Joe Mixon|RB|HOU",
  "Kenneth Walker III|RB|SEA",
  "DeVonta Smith|WR|PHI",
  "DJ Moore|WR|CHI",
  "Terry McLaurin|WR|WAS",
  "Chris Olave|WR|NO",
  "Jayden Daniels|QB|WAS",
  "Brock Bowers|TE|LV",
  "Trey McBride|TE|ARI",
  "George Kittle|TE|SF",
  "Travis Kelce|TE|KC",
  "Joe Burrow|QB|CIN",
  "Patrick Mahomes|QB|KC",
  "Zay Flowers|WR|BAL",
  "Rome Odunze|WR|CHI",
  "Xavier Worthy|WR|KC",
  "Courtland Sutton|WR|DEN",
  "Jameson Williams|WR|DET",
  "Alvin Kamara|RB|NO",
  "David Montgomery|RB|DET",
  "James Conner|RB|ARI",
  "Chuba Hubbard|RB|CAR",
  "D'Andre Swift|RB|CHI",
  "Aaron Jones|RB|MIN",
  "Baker Mayfield|QB|TB",
  "Bo Nix|QB|DEN",
  "George Pickens|WR|DAL",
  "Jaylen Waddle|WR|MIA",
  "Calvin Ridley|WR|TEN",
  "Tetairoa McMillan|WR|CAR",
  "Rashee Rice|WR|KC",
  "Jerry Jeudy|WR|CLE",
  "Jordan Addison|WR|MIN",
  "Jauan Jennings|WR|SF",
  "Deebo Samuel|WR|WAS",
  "Jakobi Meyers|WR|LV",
  "Khalil Shakir|WR|BUF",
  "Travis Etienne Jr.|RB|JAX",
  "Tony Pollard|RB|TEN",
  "Rhamondre Stevenson|RB|NE",
  "Isiah Pacheco|RB|KC",
  "Najee Harris|RB|LAC",
  "Rachaad White|RB|TB",
  "Chase Brown|RB|CIN",
  "Brian Robinson Jr.|RB|WAS",
  "J.K. Dobbins|RB|DEN",
  "Tyrone Tracy Jr.|RB|NYG",
  "Sam LaPorta|TE|DET",
  "T.J. Hockenson|TE|MIN",
  "Mark Andrews|TE|BAL",
  "David Njoku|TE|CLE",
  "Evan Engram|TE|JAX",
  "Dak Prescott|QB|DAL",
  "Justin Herbert|QB|LAC",
  "Kyler Murray|QB|ARI",
  "Brock Purdy|QB|SF",
  "Jared Goff|QB|DET",
  "C.J. Stroud|QB|HOU",
  "Jordan Love|QB|GB",
  "Chris Godwin|WR|TB",
  "Stefon Diggs|WR|NE",
  "Cooper Kupp|WR|SEA",
  "Brandon Aiyuk|WR|SF",
  "Michael Pittman Jr.|WR|IND",
  "Diontae Johnson|WR|BAL",
  "Keon Coleman|WR|BUF",
  "Ricky Pearsall|WR|SF",
  "Xavier Legette|WR|CAR",
  "Josh Downs|WR|IND",
  "Darnell Mooney|WR|ATL",
  "Christian Kirk|WR|HOU",
  "Cedric Tillman|WR|CLE",
  "Wan'Dale Robinson|WR|NYG",
  "DeMario Douglas|WR|NE",
  "Jalen McMillan|WR|TB",
  "Tre Tucker|WR|LV",
  "Bucky Irving|RB|TB",
  "Rico Dowdle|RB|DAL",
  "Zach Charbonnet|RB|SEA",
  "Jaylen Warren|RB|PIT",
  "Tyjae Spears|RB|TEN",
  "Austin Ekeler|RB|WAS",
  "Nick Chubb|RB|HOU",
  "Tank Bigsby|RB|JAX",
  "Braelon Allen|RB|NYJ",
  "Trey Benson|RB|ARI",
  "Ray Davis|RB|BUF",
  "Blake Corum|RB|LAR",
  "MarShawn Lloyd|RB|GB",
  "Kendre Miller|RB|NO",
  "Jayden Reed|WR|GB",
  "Romeo Doubs|WR|GB",
  "Dontayvion Wicks|WR|GB",
  "Christian Watson|WR|GB",
  "Tyler Lockett|WR|TEN",
  "Amari Cooper|WR|FA",
  "Keenan Allen|WR|LAC",
  "Adam Thielen|WR|CAR",
  "Gabe Davis|WR|JAX",
  "Curtis Samuel|WR|BUF",
  "Jalen Nailor|WR|MIN",
  "Adonai Mitchell|WR|IND",
  "Marvin Mims Jr.|WR|DEN",
  "DeAndre Hopkins|WR|BAL",
  "Tyler Boyd|WR|TEN",
  "Noah Brown|WR|WAS",
  "Drake Maye|QB|NE",
  "Caleb Williams|QB|CHI",
  "Trevor Lawrence|QB|JAX",
  "J.J. McCarthy|QB|MIN",
  "Tua Tagovailoa|QB|MIA",
  "Justin Fields|QB|NYJ",
  "Michael Penix Jr.|QB|ATL",
  "Cam Ward|QB|TEN",
  "Geno Smith|QB|LV",
  "Matthew Stafford|QB|LAR",
  "Bryce Young|QB|CAR",
  "Sam Darnold|QB|SEA",
  "Aaron Rodgers|QB|PIT",
  "Daniel Jones|QB|IND",
  "Russell Wilson|QB|NYG",
  "Jared Wiley|TE|KC",
  "Dallas Goedert|TE|PHI",
  "Jake Ferguson|TE|DAL",
  "Pat Freiermuth|TE|PIT",
  "Dalton Kincaid|TE|BUF",
  "Kyle Pitts|TE|ATL",
  "Colston Loveland|TE|CHI",
  "Tyler Warren|TE|IND",
  "Hunter Henry|TE|NE",
  "Jonnu Smith|TE|MIA",
  "Zach Ertz|TE|WAS",
  "Cade Otton|TE|TB",
  "Tucker Kraft|TE|GB",
  "Isaiah Likely|TE|BAL",
  "Cole Kmet|TE|CHI",
  "Juwan Johnson|TE|NO",
  "Mike Gesicki|TE|CIN",
  "Noah Fant|TE|SEA",
  "Tyler Conklin|TE|LAC",
  "Chig Okonkwo|TE|TEN",
  "Darren Waller|TE|NYG",
  "Brenton Strange|TE|JAX",
  "Ja'Tavion Sanders|TE|CAR",
  "Theo Johnson|TE|NYG",
  "Ben Sinnott|TE|WAS",
  "Will Shipley|RB|PHI",
  "Kimani Vidal|RB|LAC",
  "Isaac Guerendo|RB|SF",
  "Jordan Mason|RB|MIN",
  "Audric Estime|RB|DEN",
  "Roschon Johnson|RB|CHI",
  "Justice Hill|RB|BAL",
  "Alexander Mattison|RB|MIA",
  "Antonio Gibson|RB|NE",
  "Ezekiel Elliott|RB|FA",
  "Cam Akers|RB|NO",
  "Jerome Ford|RB|CLE",
  "D'Onta Foreman|RB|CLE",
  "Jaylen Wright|RB|MIA",
  "Dylan Sampson|RB|CLE",
  "Quinshon Judkins|RB|CLE",
  "Omarion Hampton|RB|LAC",
  "Ashton Jeanty|RB|LV",
  "TreVeyon Henderson|RB|NE",
  "RJ Harvey|RB|DEN",
  "Kaleb Johnson|RB|PIT",
  "Bhayshul Tuten|RB|JAX",
  "Dylan Laube|RB|LV",
  "Emari Demercado|RB|ARI",
  "Kenneth Gainwell|RB|PIT",
  "Miles Sanders|RB|DAL",
  "Sincere McCormick|RB|LV",
  "Chris Rodriguez Jr.|RB|WAS",
  "Ty Chandler|RB|MIN",
  "Keaton Mitchell|RB|BAL",
  "Dameon Pierce|RB|HOU",
  "Samaje Perine|RB|CIN",
  "Raheem Mostert|RB|LV",
  "Jeff Wilson Jr.|RB|MIA",
  "Clyde Edwards-Helaire|RB|NO",
  "Javonte Williams|RB|DAL",
  "Tyler Allgeier|RB|ATL",
  "Kyle Monangai|RB|CHI",
  "Woody Marks|RB|HOU",
  "Braelon Allen|RB|NYJ",
  "Isaiah Davis|RB|NYJ",
  "Sean Tucker|RB|TB",
  "Hassan Haskins|RB|LAC",
  "Chris Brooks|RB|GB",
  "Emanuel Wilson|RB|GB",
  "Alec Pierce|WR|IND",
  "Quentin Johnston|WR|LAC",
  "Joshua Palmer|WR|LAC",
  "Mike Williams|WR|PIT",
  "Van Jefferson|WR|PIT",
  "Calvin Austin III|WR|PIT",
  "Roman Wilson|WR|PIT",
  "Andrei Iosivas|WR|CIN",
  "Trenton Irwin|WR|CIN",
  "Jermaine Burton|WR|CIN",
  "Tim Patrick|WR|DET",
  "Kalif Raymond|WR|DET",
  "Allen Lazard|WR|NYJ",
  "Malachi Corley|WR|NYJ",
  "Parker Washington|WR|JAX",
  "Brian Thomas|WR|JAX",
  "Troy Franklin|WR|DEN",
  "Devaughn Vele|WR|DEN",
  "Lil'Jordan Humphrey|WR|DEN",
  "Kayshon Boutte|WR|NE",
  "Kendrick Bourne|WR|NE",
  "Mack Hollins|WR|NE",
  "Jalen Coker|WR|CAR",
  "David Moore|WR|CAR",
  "Jonathan Mingo|WR|DAL",
  "KaVontae Turpin|WR|DAL",
  "Jalen Brooks|WR|DAL",
  "Luke McCaffrey|WR|WAS",
  "Dyami Brown|WR|WAS",
  "Olamide Zaccheaus|WR|WAS",
  "John Metchie III|WR|HOU",
  "Xavier Hutchinson|WR|HOU",
  "Robert Woods|WR|HOU",
  "Tutu Atwell|WR|LAR",
  "Jordan Whittington|WR|LAR",
  "Demarcus Robinson|WR|LAR",
  "Jalen Tolbert|WR|DAL",
  "Brandin Cooks|WR|DAL",
  "Dont'e Thornton Jr.|WR|LV",
  "Jack Bech|WR|LV",
  "Elic Ayomanor|WR|TEN",
  "Chimere Dike|WR|TEN",
  "Luther Burden III|WR|CHI",
  "Matthew Golden|WR|GB",
  "Jayden Higgins|WR|HOU",
  "Emeka Egbuka|WR|TB",
  "Travis Hunter|WR|JAX",
  "Isaiah Bond|WR|CLE",
  "Jacks Bech|WR|LV",
  "Pat Bryant|WR|DEN",
  "Kyle Williams|WR|NE",
  "Savion Williams|WR|GB",
  "Jaylin Noel|WR|HOU",
  "Isaac TeSlaa|WR|DET",
  "Jalen Royals|WR|KC",
  "Darius Slayton|WR|NYG",
  "Jalin Hyatt|WR|NYG",
  "Malik Washington|WR|MIA",
  "Odell Beckham Jr.|WR|FA",
  "JuJu Smith-Schuster|WR|KC",
  "Mecole Hardman|WR|KC",
  "Skyy Moore|WR|KC",
  "Justin Watson|WR|KC",
  "Nick Westbrook-Ikhine|WR|MIA",
  "River Cracraft|WR|MIA",
  "A.T. Perry|WR|NO",
  "Cedrick Wilson Jr.|WR|NO",
  "Equanimeous St. Brown|WR|NO",
  "Chris Moore|WR|WAS",
  "Sterling Shepard|WR|TB",
  "Rakim Jarrett|WR|TB",
  "Trey Palmer|WR|TB",
  "Justin Jefferson|WR|MIN",
  "Jordan Love|QB|GB",
  "Kirk Cousins|QB|ATL",
  "Spencer Rattler|QB|NO",
  "Tyler Shough|QB|NO",
  "Joe Flacco|QB|CLE",
  "Dillon Gabriel|QB|CLE",
  "Shedeur Sanders|QB|CLE",
  "Mac Jones|QB|SF",
  "Aidan O'Connell|QB|LV",
  "Gardner Minshew|QB|KC",
  "Jacoby Brissett|QB|ARI",
  "Marcus Mariota|QB|WAS",
  "Tyrod Taylor|QB|NYJ",
  "Cooper Rush|QB|DAL",
  "Andy Dalton|QB|CAR",
  "Jameis Winston|QB|NYG",
  "Mason Rudolph|QB|PIT",
  "Will Levis|QB|TEN",
  "Anthony Richardson|QB|IND",
  "Joe Milton III|QB|NE",
  "Drew Lock|QB|SEA",
  "Davis Mills|QB|HOU",
  "Trey Lance|QB|LAC",
  "Sam Howell|QB|MIN",
  "Hendon Hooker|QB|DET",
  "Austin Hooper|TE|NE",
  "Gerald Everett|TE|CHI",
  "Dawson Knox|TE|BUF",
  "Foster Moreau|TE|NO",
  "Taysom Hill|TE|NO",
  "Noah Gray|TE|KC",
  "Durham Smythe|TE|CHI",
  "Grant Calcaterra|TE|PHI",
  "Kylen Granson|TE|PHI",
  "Lucas Krull|TE|DEN",
  "Adam Trautman|TE|DEN",
  "Brock Wright|TE|DET",
  "Josh Oliver|TE|MIN",
  "Johnny Mundt|TE|JAX",
  "Elijah Arroyo|TE|SEA",
  "Mason Taylor|TE|NYJ",
  "Gunnar Helm|TE|TEN",
  "Terrance Ferguson|TE|LAR",
  "Harold Fannin Jr.|TE|CLE",
  "Oronde Gadsden II|TE|LAC",
  "Jaheim Bell|TE|NE",
  "Tip Reiman|TE|ARI",
  "Erick All Jr.|TE|CIN",
  "AJ Barner|TE|SEA",
  "Charlie Kolar|TE|BAL",
  "Daniel Bellinger|TE|NYG",
  "Mo Alie-Cox|TE|IND",
  "Kendre Miller|RB|NO",
  "Jamaal Williams|RB|NO",
  "Deuce Vaughn|RB|DAL",
  "Hunter Luepke|RB|DAL",
  "Ameer Abdullah|RB|LV",
  "Pierre Strong Jr.|RB|CLE",
  "Craig Reynolds|RB|DET",
  "Sione Vaki|RB|DET",
  "Jaleel McLaughlin|RB|DEN",
  "Michael Burton|RB|DEN",
  "Dare Ogunbowale|RB|HOU",
  "British Brooks|RB|HOU",
  "Patrick Taylor|RB|SF",
  "Elijah Mitchell|RB|KC",
  "Carson Steele|RB|KC",
  "Keilan Robinson|RB|JAX",
  "LeQuint Allen Jr.|RB|JAX",
  "Deneric Prince|RB|KC",
  "Eric Gray|RB|NYG",
  "Dante Miller|RB|NYG",
  "Chris Collier|RB|NYJ",
  "Isaiah Spiller|RB|LV",
  "Kimani Vidal|RB|LAC",
  "J.K. Dobbins|RB|DEN",
  "Michael Carter|RB|ARI",
  "Emari Demercado|RB|ARI",
  "DeeJay Dallas|RB|ARI",
  "Ty Johnson|RB|BUF",
  "Frank Gore Jr.|RB|BUF",
  "Reggie Gilliam|RB|BUF",
  "Alec Ingold|RB|MIA",
  "Jeff Wilson Jr.|RB|MIA",
  "Evan Hull|RB|IND",
  "Trey Sermon|RB|IND",
  "Salvon Ahmed|RB|IND",
];

const KICKERS = [
  "Brandon Aubrey|K|DAL",
  "Chris Boswell|K|PIT",
  "Cameron Dicker|K|LAC",
  "Ka'imi Fairbairn|K|HOU",
  "Jake Bates|K|DET",
  "Harrison Butker|K|KC",
  "Justin Tucker|K|FA",
  "Younghoe Koo|K|ATL",
  "Jake Elliott|K|PHI",
  "Tyler Bass|K|BUF",
  "Jason Myers|K|SEA",
  "Chase McLaughlin|K|TB",
  "Matt Gay|K|IND",
  "Cameron Santos|K|LAR",
  "Wil Lutz|K|DEN",
  "Evan McPherson|K|CIN",
  "Jason Sanders|K|MIA",
  "Jake Moody|K|SF",
  "Cairo Santos|K|CHI",
  "Daniel Carlson|K|LV",
  "Nick Folk|K|NE",
  "Blake Grupe|K|NO",
  "Eddy Pineiro|K|CAR",
  "Matt Prater|K|ARI",
  "Greg Joseph|K|NYJ",
  "Graham Gano|K|NYG",
  "Brandon McManus|K|GB",
  "Chad Ryland|K|ARI",
  "Joshua Karty|K|LAR",
  "Will Reichard|K|MIN",
  "Anders Carlson|K|SF",
  "Spencer Shrader|K|NYJ",
];

const DSTS = [
  "Baltimore Ravens|DST|BAL",
  "Philadelphia Eagles|DST|PHI",
  "San Francisco 49ers|DST|SF",
  "Buffalo Bills|DST|BUF",
  "Pittsburgh Steelers|DST|PIT",
  "Denver Broncos|DST|DEN",
  "Minnesota Vikings|DST|MIN",
  "Green Bay Packers|DST|GB",
  "Kansas City Chiefs|DST|KC",
  "New York Jets|DST|NYJ",
  "Dallas Cowboys|DST|DAL",
  "Houston Texans|DST|HOU",
  "Cleveland Browns|DST|CLE",
  "Detroit Lions|DST|DET",
  "Los Angeles Chargers|DST|LAC",
  "Miami Dolphins|DST|MIA",
  "Seattle Seahawks|DST|SEA",
  "Tampa Bay Buccaneers|DST|TB",
  "Cincinnati Bengals|DST|CIN",
  "Chicago Bears|DST|CHI",
  "Indianapolis Colts|DST|IND",
  "Los Angeles Rams|DST|LAR",
  "New Orleans Saints|DST|NO",
  "Atlanta Falcons|DST|ATL",
  "Washington Commanders|DST|WAS",
  "New York Giants|DST|NYG",
  "Arizona Cardinals|DST|ARI",
  "Las Vegas Raiders|DST|LV",
  "Jacksonville Jaguars|DST|JAX",
  "Tennessee Titans|DST|TEN",
  "New England Patriots|DST|NE",
  "Carolina Panthers|DST|CAR",
];

function slug(name, team, pos) {
  return `${name}-${team}-${pos}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function projected(pos, posRank) {
  const table = {
    QB: [318, 5.1],
    RB: [292, 2.35],
    WR: [278, 2.05],
    TE: [214, 3.15],
    K:  [148, 1.35],
    DST:[142, 1.55],
  };
  const [base, slope] = table[pos];
  return Math.round((base - posRank * slope) * 10) / 10;
}

function parseRow(row) {
  const [name, position, team] = row.split("|");
  return { name, position, team: team === "FA" ? "FA" : team };
}

const seen = new Set();
const unique = [];
for (const row of RAW) {
  const parsed = parseRow(row);
  const id = slug(parsed.name, parsed.team, parsed.position);
  if (seen.has(id)) continue;
  seen.add(id);
  unique.push({ id, ...parsed });
  if (unique.length >= 260) break;
}
for (const row of [...KICKERS, ...DSTS]) {
  const parsed = parseRow(row);
  const id = slug(parsed.name, parsed.team, parsed.position);
  if (seen.has(id)) continue;
  seen.add(id);
  unique.push({ id, ...parsed });
}

const posCounts = {};
const players = unique.map((p, index) => {
  posCounts[p.position] = (posCounts[p.position] || 0) + 1;
  const posRank = posCounts[p.position];
  const rank = index + 1;
  const adp = Math.round((rank + (index % 7) * 0.17 - 0.4) * 10) / 10;
  return {
    id: p.id,
    name: p.name,
    position: p.position,
    team: p.team,
    rank,
    adp: Math.max(1, adp),
    byeWeek: BYE[p.team] ?? 10,
    posRank,
    projectedPoints: Math.max(28, projected(p.position, posRank)),
  };
});

if (players.length < 300) {
  throw new Error(`Need ~300 players, generated ${players.length}`);
}

const outDir = join(root, "data");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "players.json"), JSON.stringify(players, null, 2) + "\n");
console.log(`Wrote ${players.length} players to data/players.json`);
console.log(Object.fromEntries(Object.entries(posCounts)));
